main: world.fluff.FluffWorldIntegration
name: FluffWorldIntegration
version: 1.5.1
author: Fluff
description: Fluff's Plugin
commands:
  points:
    description: (FWMC) Displays your FWMC points
    usage: /points
  chatcolor:
    description: (FWMC) Changes your color in the chat
    usage: /chatcolor color
  coords:
    description: (FWMC) Broadcast your coordinates
    usage: /coords
  register:
    description: (FWMC) Link your FW account
    usage: /register FWusername