main: world.fluff.FluffWorldIntegration
name: FluffWorldIntegration
version: 1.7.3
author: Fluff
description: Fluff's Plugin
commands:
  points:
    description: (FWMC) Displays FWMC points
    usage: /points [MCusername]
  chatcolor:
    description: (FWMC) Changes your color in the chat
    usage: /chatcolor <color>
  coords:
    description: (FWMC) Broadcast your coordinates
    usage: /coords
  register:
    description: (FWMC) Link your FW account
    usage: /register <FWusername>
  withdraw:
    description: (FWMC) Withdraw FWMC points into a FWMC Points Ticket item
    usage: /withdraw <points to withdraw>
  bedspawn:
    description: (FWMC) Get the coordinates of your bed spawn's location, or broadcast it to other players
    usage: /bedspawn [broadcast]
