main: world.fluff.Main
name: FluffWorldMinecraft
version: 0.1
commands:
  chatcolor:
    description: Change your chat color
    usage: /chatcolor
  share:
    description: Share
    usage: /share
depend: [MinimapAPI]
